--SQLQuery100-CREATE FUNCTION IsHoliday.sql
USE PD_321;
GO

ALTER FUNCTION IsHoliday
(
	@date	AS	DATE
)
RETURNS BIT
AS
BEGIN
	IF	@date	>=	DATEFROMPARTS(YEAR(@date),1,1)
	AND	@date	<=	DATEFROMPARTS(YEAR(@date),1,14 - DATEPART(WEEKDAY,DATEFROMPARTS(YEAR(@date) - 1,12,31)))
	OR	@date	=	DATEFROMPARTS(YEAR(@date),2,23)
	OR	@date	=	DATEFROMPARTS(YEAR(@date),3,8)
	OR	@date	>=	DATEFROMPARTS(YEAR(@date),5,1)
	AND	@date	<=	DATEFROMPARTS(YEAR(@date),5,10)
	OR	@date	>=	DATEFROMPARTS(YEAR(@date),7,31 - DATEPART(WEEKDAY,DATEFROMPARTS(YEAR(@date),7,31)) + 1)
	AND	@date	<=	DATEFROMPARTS(YEAR(@date),8,20 - DATEPART(WEEKDAY,DATEFROMPARTS(YEAR(@date),7,31)) + 1)
	OR	@date	>=	DATEFROMPARTS(YEAR(@date),12,31 - DATEPART(WEEKDAY,DATEFROMPARTS(YEAR(@date),12,31)) + 1)
	AND	@date	<=	DATEFROMPARTS(YEAR(@date),12,31)
	BEGIN
		RETURN 1;
	END
	RETURN 0;
END